name: test
on: workflow_dispatch
env: 
   ASHMITA_SAWANT_ACCOUNTID: ${{secrets.ASHMITA_SAWANT_ACCOUNTID}}
jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
    secret-number: ${{steps.sets-a-secret.outputs.secret-number}}
   steps:
      - uses: actions/checkout@v2
      - id: sets-a-secret
        run: |
              git show -s --format=%ci <commit> DeploymentConfiguration/ProcessDetails.Crow_Demo.dev.json
              git log -1 --pretty="format:%ct" DeploymentConfiguration/ProcessDetails.Crow_Demo.dev.json

              
