name: test
on: workflow_dispatch
env: 
   ASHMITA_SAWANT_ACCOUNTID: ${{secrets.ASHMITA_SAWANT_ACCOUNTID}}
jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
    secret-number: ${{steps.sets-a-secret.outputs.secret-number}}
   steps:
      - uses: actions/checkout@v2
      - id: sets-a-secret
        run: |
              git ls-tree -r --name-only HEAD | ForEach-Object { "$(git log -1 --format="%ai" -- "$_")`t$_"`" }


              
